name: Docker Image CI

on:
  push:
    branches: [ "build" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag besmillahibrahimi/wordpress:latest

    - name: Push Docker image
      run: docker push besmillahibrahimi/wordpress:latest
